[server]
host = "127.0.0.1"
port = 3000

[catalog]
type = "sqlite"
## Postgres example
#[catalog]
#type = "postgres"
#host = "localhost"
#port = 5432
#database = "runtime"
#user = "runtimeuser"
#password =

[storage]
type = "s3"
bucket = "ducklake-data"
region = "us-west-2"
endpoint = "http://localhost:9000"
access_key = "minioadmin"
secret_key = "minioadmin"
## Filesystem example
#[storage]
#type = "filesystem"

[paths]
#cache_dir = "~/.hotdata/runtimedb/cache"

[liquid_cache]
enabled = true
max_cache_bytes = 5368709120 # 1GB (optional defaults to 1GB)
# cache_dir = "/path/to/cache"  # optional, defaults to {base_dir}/liquid_cache
